<?php
/**
 * Created by PhpStorm.
 * User: wanga
 * Date: 2018/11/3
 * Time: 14:46
 */

namespace app\facade;

use think\Facade;

class Auth extends Facade
{
    protected static function getFacadeClass()
    {
//        parent::getFacadeClass(); // TODO: Change the autogenerated stub
        return 'think\auth\Auth';
    }
}